package com.generics;
/**
 * 各种水彩颜色的枚举
 * */
public enum Watercolors {
    ZINC,LEMON_YELLOW,MEDIUM_YELLOW,DEEP_YELLOW,ORANGE,BRILLIANT_RED,CRIMSON,MAGENTA,ROSE_MADDER,VIOLET,CERULEAN_BLUE_HUE,
    PERMANENT_GREEN,VIRIDIAN_HUE,SAP_GREEN,YELLOW_OCHRE,BURNT_SIENNA,RAW_UMBER,BURNT_UMBER,PAYNES_GRAY,IVORY_BLACK
}
